apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone-project
  labels:
    app: breakingbad
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: breakingbad
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: breakingbad
    spec:
      containers:
        - name: breakingbad-app
          image: 592339293101.dkr.ecr.us-east-1.amazonaws.com/breakingbad
          ports:
            - containerPort: 80
