apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: udacity-capstone
  region: us-east-1

vpc:
  id: vpc-0d11d25889a53825e
  cidr: "10.0.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-02d855bdc0392c7c5
      us-east-1b:
        id: subnet-0148750ccd5fbc3b6

nodeGroups:
  - name: capstone-eks-workers
    instanceType: t2.medium
    desiredCapacity: 2
