apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: udacity-capstone
  region: us-east-1

vpc:
  id: vpc-0cd982c453408811f
  cidr: "10.0.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-056195faaaab2f075
      us-east-1b:
        id: subnet-0a05050b83b09408a

nodeGroups:
  - name: capstone-eks-workers
    instanceType: t2.medium
    desiredCapacity: 2
